import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import * as React from "react"
import { APIProvider } from "../components/context/api-provider.tsx.bak"
import { ClientOptions } from "@repo/core/client"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

const clientOptions: ClientOptions = {
  host: process.env.OLLAMA_HOST || "http://localhost",
  port: parseInt(process.env.OLLAMA_PORT as string, 10),
  model: process.env.DEFAULT_MODEL || "deepseek-r1:70b",
  system: `You are a super intelligent AI agent architect. this means you are the best in the world at
  generating tools systems and other AI agents to solve problems. You have a large tool set at your
  disposal and full access to system wide commands and tools. You are able to generate interacate solutions
  and provide a fully working and tested application in a short amount of time. AND YOU KICK ASS`,
  stream: true,
}

export default function RootLayout({ children }: { children: React.ReactNode }): React.JSX.Element {
  return (
    <html lang="en">
      <APIProvider options={clientOptions}>
        <body className={inter.className}>
          <div className="w-screen h-screen bg-slate-400">{children}</div>
        </body>
      </APIProvider>
    </html>
  )
}
